interface ITournament {
  id: number,
  date: string,
  title?: string,
  link?: string,
  nomination?: string,
  weekend?: boolean,
  satellite: boolean,
  division: string,
  city: string,
  ages: string[],
  echelons?: string[],
}


export const tournaments : ITournament[] = [
  {
    "id": 0,
    "date": "13 сентября 2025",
    "nomination": "Итальянская дуэльная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 1,
    "date": "27 сентября 2025",
    "nomination": "Итальянская дуэльная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 2,
    "date": "4 октября 2025",
    "nomination": "Дуэльная рапира",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 23,
    "date": "5 октября 2025",
    "nomination": "Рапира Ренессанса (команды)",
    "link": "https://vk.com/goldenfalconopenchamp",
    "weekend": false,
    "satellite": true,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 3,
    "date": "25 октября 2025",
    "nomination": "Дуэльная рапира",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 4,
    "date": "25 октября 2025",
    "nomination": "Английская гимнастическая сабля",
    "weekend": false,
    "satellite": false,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 26,
    "date": "26 октября 2025",
    "title": "Кубок Сибири",
    "link": "https://vk.com/dff_siberian_cup",
    "nomination": "Рапира Ренессанса (команды)",
    "weekend": false,
    "satellite": true,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 21,
    "date": "26 октября 2025",
    "title": "Кубок Ярославля",
    "link": "https://vk.com/autumn_hemacup_yar",
    "nomination": "Английская гимнастическая сабля (команды)",
    "weekend": false,
    "satellite": true,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },

  {
    "id": 5,
    "date": "9 ноября 2025",
    "nomination": "Фехтшуле",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 6,
    "date": "23 ноября 2025",
    "nomination": "Фехтшуле",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 29,
    "date": "29-30 ноября 2025",
    "title": "Кубок Востока",
    "link": "https://vk.com/hemakidschel",
    // "nomination": "Фехтшуле (команды)",
    "weekend": true,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Подростки",
    ],
  },
  {
    "id": 40,
    "date": "6-7 декабря 2025",
    "title": "HEMA Panda",
    "weekend": true,
    "satellite": false,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Подростки",
    ],
  },
  {
    "id": 7,
    "date": "13 декабря 2025",
    "nomination": "Рапира Ренессанса (дага)",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 8,
    "date": "20 декабря 2025",
    "nomination": "Рапира Ренессанса (дага)",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 9,
    "date": "18 января 2026",
    "nomination": "Длинный меч",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 10,
    "date": "25 января 2026",
    "nomination": "Длинный меч",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
// TODO
  {
    "id": 30,
    "date": "31-1 января-февраля 2026",
    "title": "Hello Sword",
    "link": "https://vk.com/hellosword",
    "nomination": "Длинный меч, Рапира, Дуэльная сабля, Меч и баклер",
    "weekend": true,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
    ],
  },
  {
    "id": 11,
    "date": "14 февраля 2026",
    "nomination": "Итальянская дуэльная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 12,
    "date": "14 февраля 2026",
    "nomination": "Австрийская Военная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 24,
    "date": "15 февраля 2026",
    "nomination": "Итальянская дуэльная сабля (команды)",
    "weekend": false,
    "satellite": true,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 22,
    "date": "15 февраля 2026",
    "title": "Зимний Кубок Ярославля",
    "link": "https://vk.com/winter_hemacup_yar",
    "nomination": "Итальянский длинный меч, Дуэльная рапира",
    "weekend": false,
    "satellite": true,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 13,
    "date": "21 февраля 2026",
    "nomination": "Австрийская Военная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 27,
    "date": "22 февраля 2026",
    "title": "Кубок Сибири",
    "link": "https://vk.com/dff_siberian_cup",
    "nomination": "Итальянская дуэльная сабля (команды)",
    "weekend": false,
    "satellite": true,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 15,
    "date": "14 марта 2026",
    "nomination": "Итальянский длинный меч",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 28,
    "date": "15 марта 2026",
    "title": "Кубок Сибири",
    "link": "https://vk.com/dff_siberian_cup",
    "nomination": "Фехтшуле (команды)",
    "weekend": false,
    "satellite": true,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 14,
    "date": "28 марта 2026",
    "nomination": "Итальянский длинный меч",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 25,
    "date": "29 марта 2026",
    "title": "Кубок Золотого Сокола",
    "link": "https://vk.com/goldenfalconcup",
    "nomination": "Итальянский длинный меч, Фехтшуле",
    "weekend": true,
    "satellite": true,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
      "Подростки",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 16,
    "date": "11 апреля 2026",
    "nomination": "Рапира Ренессанса",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 17,
    "date": "19 апреля 2026",
    "nomination": "Рапира Ренессанса",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 18,
    "date": "19 апреля 2025",
    "nomination": "Австрийская Военная сабля",
    "weekend": false,
    "satellite": false,
    "division": "Центр",
    "city": "Ярославль",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
    {
    "id": 31,
    "date": "1-3 мая 2026",
    "title": "Молодая Гвардия",
    // "nomination": "Фехтшуле (команды)",
    "link": "https://vk.com/golden_falcon_junior_tournament",
    "weekend": true,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
    ],
  },
  {
    "id": 19,
    "date": "17 мая 2026",
    "nomination": "Английская гимнастическая сабля",
    "weekend": false,
    "satellite": false,
    "division": "Урал",
    "city": "Челябинск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
  {
    "id": 20,
    "date": "24 мая 2026",
    "nomination": "Английская гимнастическая сабля",
    "weekend": false,
    "satellite": false,
    "division": "Сибирь",
    "city": "Новосибирск",
    "ages": [
      "Взрослые",
    ],
    "echelons": [
      "Начинающие",
      "Начинающие+",
      "Общий",
    ],
  },
];